name: Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  codespell:
    name: Check spelling all files with codespell
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell==2.1.0
      - name: Check spelling with codespell
        run: codespell --ignore-words=codespell.txt || exit 1
